name: Update README

on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: 'actions-go/go-install@main'
        id: install
        with:
          module: "github.com/taciturnaxolotl/markscribe@HEAD"

      - name: generate readme
        env:
          WAKATIME_API_KEY: 6f0c8563-d367-414b-97cf-b3a0c5c9aa33
          WAKATIME_URL: https://hackatime.hackclub.com/api/hackatime/v1
        run: ${{ steps.install.outputs.install-path }} -write README.md templates/README.md.tpl
