name: Update README

on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: 'actions-go/go-install@main'
        id: install
        with:
          module: "github.com/taciturnaxolotl/markscribe@HEAD"

      - name: generate readme
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }}
        run: ${{ steps.install.outputs.install-path }} -write README.md templates/README.md.tpl
